// eslint-disable-next-line
export const LIST_ACTIONS = {
  ITEM_PREVIEW: 'ITEM_PREVIEW',
  ITEM_VIEW: 'ITEM_VIEW',
  ITEM_ADD: 'ITEM_ADD',
  ITEM_CLEAR: 'ITEM_CLEAR',
};

export const DEVICES_ACTIONS = {
  ITEM_PREVIEW: 'DEVICES_ITEM_PREVIEW',
  ITEM_VIEW: 'DEVICES_ITEM_VIEW',
  ITEM_ADD: 'DEVICES_ITEM_ADD',
  ITEM_REMOVE: 'DEVICES_ITEM_REMOVE',
};
